name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Run multiple lines
        run: |
          echo "First Output"
          echo "Second Output"
      - name: Print goodbye
        run: echo "Done - bye!"
      
